[workspace]
members = ["ftn"]
resolver = "2"

[workspace.package]
authors = [
    "Amit Upadhyay <upadhyay@gmail.com>",
]
edition = "2024"
description = "FTN: FifthTry Network"
license = "UPL-1.0"
repository = "https://github.com/FifthTry/ftn"
homepage = "https://www.fifthtry.com/ftn/"
publish = true
rust-version = "1.85"

[profile.release]
strip = true

[workspace.dependencies]
# Please do not specify a dependency more precisely than needed. If version "1" works, do
# not specify "1.1.42". This reduces the number of total dependencies. For example, if you
# specify 1.1.42 and someone else who only needed "1" also specified 1.1.37, we end up having
# the same dependency getting compiled twice.
#
# In the future, we may discover that our code does not indeed work with "1", say it ony works
# for 1.1 onwards, or 1.1.25 onwards, in which case use >= 1.1.25 etc. Saying our code
# only works for 1.1.42 and not 1.1.41 nor 1.1.43 is really weird, and most likely wrong.
#
# If you are not using the latest version intentionally, please do not list it in this section
# and create its own [dependencies.<name>] section. Also, document it with why are you not
# using the latest dependency, and what is the plan to move to the latest version.
clap = { version = "4", features = ["derive"] }
thiserror = "2"
directories = "6.0.0"
file-guard = "0.2.0"
iroh = "0.34"
tokio = { version = "1", features = ["full"] }
