[package]
name = "ftn"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true
description = "FTNet: FifthTry Network"


[dependencies]
clap.workspace = true
tokio.workspace = true
