[package]
name = "ftnet-common"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description = "shared code for control-backend-wasm and FTNet"

[dependencies]
serde.workspace = true
