[package]
name = "ftnet-sdk"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
description = "shared code for control-backend-wasm and FTNet"
homepage.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
