name: Upload ftnet.fifthtry.site to FifthTry

on:
  push:
    branches: [ main ]
    paths:
      - ftnet.fifthtry.site/**
      - control-backend-wasm/**
      - common/**
      - scripts/*.sh
      - .github/workflows/app-to-ft.yml
      - Cargo.toml


jobs:
  upload-to-fifthtry:
    runs-on: ubuntu-latest
    env:
      FIFTHTRY_SITE_WRITE_TOKEN: ${{ secrets.FT_FTNET_APP }}
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - run: ./scripts/publish-app.sh >> $GITHUB_STEP_SUMMARY
