name: Upload ftnet-template to FifthTry

on:
  push:
    branches: [ main ]
    paths:
      - ftnet-template.fifthtry.site/**
      - .github/workflows/ftnet-template-to-ft.yml


jobs:
  upload-to-fifthtry:
    runs-on: ubuntu-latest
    env:
      FIFTHTRY_SITE_WRITE_TOKEN: ${{ secrets.FT_FTNET_TEMPLATE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: sh -c "$(curl -fsSL https://fastn.com/install.sh)"
      - name: Upload to FifthTry using fastn
        run: cd ftnet-template.fifthtry.site/ && fastn upload ftnet-template >> $GITHUB_STEP_SUMMARY
