name: Deploy kulfi.app

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'kulfi.app/**'
      - '.github/workflows/kulfi-website-to-ft.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions
      FIFTHTRY_SITE_WRITE_TOKEN: ${{ secrets.FT_KULFI_WWW }}
    steps:
      - uses: actions/checkout@v4
      - run: source <(curl -fsSL https://fastn.com/install.sh)
      - run: |
          cd kulfi.app
          echo "Using $(fastn --version) to upload ftnet.in to FifthTry"
          # Requires FIFTHTRY_SITE_WRITE_TOKEN to be set
          fastn upload kulfi-www >> $GITHUB_STEP_SUMMARY
