# TODO(siddhantk232): build for windows
name: Create a new skynet release

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release Version (will be prefixed with "skynet-")'
        required: true
      productionRelease:
        type: boolean
        description: Mark release as production ready
jobs:
  release-ubuntu:
    name: Build for Linux
    # using the oldest available ubuntu on github CI to provide maximum compatibility with glibc versions
    # update SKYNET_RELEASE_TEMPLATE with the glibc version
    # on ubuntu-20.04, glibc version is 2.31
    runs-on: ubuntu-20.04
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: print rustc version
        run: rustc --version
      - name: cargo build (linux)
        run: cargo build --release --bin skynet
      - name: print skynet version
        run: ./target/release/skynet --version
      - name: print file info
        run: |
          file ./target/release/skynet
          ldd ./target/release/skynet
      - uses: actions/upload-artifact@v4
        with:
          name: linux_x86_64
          path: target/release/skynet
  release-macos:
    name: Build for MacOS
    # don't use later versions, as else our binary will be built for arm64,
    # and will not work on older macs that are based on x86_64 (intel)
    # https://github.com/fastn-stack/fastn/issues/2099
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: print rustc version
        run: rustc --version
      - name: Run Build
        id: build-macos
        continue-on-error: false
        run: cargo build --release --bin skynet
      - name: print skynet version
        run: ./target/release/skynet --version
      - name: print file info
        run: |
          file ./target/release/skynet
          otool -L ./target/release/skynet
      - uses: actions/upload-artifact@v4
        with:
          name: macos_x64_latest
          path: |
            target/release/skynet
  create-release:
    name: Create github tag and release
    runs-on: ubuntu-latest
    needs: [ release-ubuntu, release-macos ]
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: macos_x64_latest
          path: ~/download/macos
      - uses: actions/download-artifact@v4
        with:
          name: linux_x86_64
          path: ~/download/linux
      - name: Rename assets
        run: |
          mv ~/download/macos/skynet ~/download/macos/skynet_macos_x86_64
          mv ~/download/linux/skynet ~/download/linux/skynet_linux_x86_64
      - name: Update .github/SKYNET_RELEASE_TEMPLATE.md
        run: |
          sed -i "s/GITHUB_SHA/${GITHUB_SHA}/g" .github/SKYNET_RELEASE_TEMPLATE.md
          sed -i "s/DATE/$(date)/g" .github/SKYNET_RELEASE_TEMPLATE.md
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "~/download/macos/skynet_macos_x86_64,~/download/linux/skynet_linux_x86_64"
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: skynet-${{ github.event.inputs.releaseTag }}
          prerelease: ${{ github.event.inputs.productionRelease && github.event.inputs.productionRelease == 'false' }}
          bodyFile: .github/SKYNET_RELEASE_TEMPLATE.md
